name = "ParallelismHints"
uuid = "46c41b0e-a2c8-4d01-b46f-57b962fbffd7"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com> and contributors"]
version = "0.1.0-DEV"

[deps]
ContextVariablesX = "6add18c4-b38d-439d-96f6-d6bc489c04c5"
ExternalDocstrings = "e189563c-0753-4f5e-ad5c-be4293c83fb4"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"

[compat]
julia = "1.6"
